[PTT-116] add endpoint payments
pagopa/hub-pa-api pull request #31
Opened 2021-04-23 14:52 UTC by filma80

This PR proposes to add endpoints for transform the csv and load into DB.
#### List of Changes
-Create new controller PaymentsController
-Create new service PaymentService and IuvCodeGenerator
-Create  the entity for the structure of DB
-Create all the DTOs
-Create the converters from model to dto and from model to model

#### Motivation and Context

The new endpoint is necessary for save into the DB the new structure from the csv file
#### How Has This Been Tested?

-Suite of integraiton tests
-Manual Tests via Swagger-UI
-The failure cases will be tested in a new PR
#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2021-04-23 15:40 UTC, GiovanniMancini commented on docker-compose.yml
> +      - SERVICEMANAGEMENT_PATH==http://localhost:8083/
This line is apprently wrong, as it uses `==` operator. Could you check please?

2021-04-23 15:55 UTC, GiovanniMancini commented on upload-payments/src/main/java/it/gov/pagopa/hubpa/uploadpayments/mapping/ConvertUploadCsvModelToPaymentsModel.java
>      private static final String TAXONOMY_PRIMARY=System.getenv().get("TAXONOMY_PRIMARY");
Is taxonomy a property of the service? In such case I dont think it's a good idea set them here as env variables

2021-04-23 15:56 UTC, GiovanniMancini requested changes
We should check better how to model the taxonomy. Please resolve conflict with the main branch

2021-04-23 15:58 UTC, filma80 commented on upload-payments/src/main/java/it/gov/pagopa/hubpa/uploadpayments/mapping/ConvertUploadCsvModelToPaymentsModel.java
>      private static final String TAXONOMY_PRIMARY=System.getenv().get("TAXONOMY_PRIMARY");
I'll open a new task for manage it

2021-04-23 15:58 UTC, filma80 commented on docker-compose.yml
> +      - SERVICEMANAGEMENT_PATH==http://localhost:8083/
i correct it

2021-04-23 16:16 UTC, GiovanniMancini commented on docker-compose.yml
>        - JMS_AZURA_CONNECTION_STRING=
Please rename this variables as JMS_AZURE_xxx

2021-04-23 16:24 UTC, filma80 commented on docker-compose.yml
>        - JMS_AZURA_CONNECTION_STRING=
done

2021-04-23 16:24 UTC, GiovanniMancini commented on payments/src/main/resources/application.properties
> +iuv.generate.auxDigit=3
Is it right to have here static values?

2021-04-23 16:31 UTC, GiovanniMancini requested changes
I've seen you have merged main, but we still have conflicts

2021-04-23 19:51 UTC, filma80 commented on payments/src/main/resources/application.properties
> +iuv.generate.auxDigit=3
done

2021-04-27 07:36 UTC, GiovanniMancini commented
@filma80 the conflict was related to a residual file in JOB microservice. I got rid of it. Anyway we can add it at a later time if it proves to be needed

2021-04-27 07:36 UTC, merged